/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RedSocial;


import java.awt.Color;

/**
 *
 * @author Mau
 */
public class comP_1 extends javax.swing.JPanel {

    
    public comP_1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        nombreL = new javax.swing.JLabel();
        usuarioL = new javax.swing.JLabel();
        contraseñaL = new javax.swing.JLabel();
        pass2L = new javax.swing.JLabel();
        mail2L = new javax.swing.JLabel();
        celularL = new javax.swing.JLabel();
        fotoL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mailL = new javax.swing.JLabel();
        datosP = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        nombreText = new javax.swing.JTextField();
        usuarioText = new javax.swing.JTextField();
        mailText = new javax.swing.JTextField();
        mail2Text = new javax.swing.JTextField();
        celularText = new javax.swing.JTextField();
        passText = new javax.swing.JPasswordField();
        pass2Text = new javax.swing.JPasswordField();
        foto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreL.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nombreL.setText("Nombre completo:");

        usuarioL.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        usuarioL.setText("Nombre de usuario:");

        contraseñaL.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        contraseñaL.setText("Contraseña:");

        pass2L.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        pass2L.setText("Repita la contraseña:");

        mail2L.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mail2L.setText("repita su E-mail:");

        celularL.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        celularL.setText("Numero de celular:");

        fotoL.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fotoL.setText("Foto de perfil:");

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("CREAR CUENTA DE TIPO COMENSAL");

        mailL.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mailL.setText("E-mail:");

        datosP.setOpaque(false);
        datosP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        datosP.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 570, 10));
        datosP.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 570, 10));
        datosP.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 570, 10));
        datosP.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 570, 10));
        datosP.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 570, 10));
        datosP.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 570, 10));
        datosP.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 570, 10));

        nombreText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nombreText.setForeground(new java.awt.Color(204, 204, 204));
        nombreText.setText("Ingrese su nombre completo");
        nombreText.setBorder(null);
        nombreText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreTextMousePressed(evt);
            }
        });
        datosP.add(nombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 570, -1));

        usuarioText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        usuarioText.setForeground(new java.awt.Color(204, 204, 204));
        usuarioText.setText("Ingrese el nombre con el que iniciará sesión");
        usuarioText.setBorder(null);
        usuarioText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioTextMousePressed(evt);
            }
        });
        datosP.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 570, -1));

        mailText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mailText.setForeground(new java.awt.Color(204, 204, 204));
        mailText.setText("Ingrese su e-mail");
        mailText.setBorder(null);
        mailText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mailTextMousePressed(evt);
            }
        });
        datosP.add(mailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 570, -1));

        mail2Text.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mail2Text.setForeground(new java.awt.Color(204, 204, 204));
        mail2Text.setText("Repita su e-mail");
        mail2Text.setBorder(null);
        mail2Text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mail2TextMousePressed(evt);
            }
        });
        datosP.add(mail2Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 570, -1));

        celularText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        celularText.setForeground(new java.awt.Color(204, 204, 204));
        celularText.setText("Ingrese su número de celular");
        celularText.setBorder(null);
        celularText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                celularTextMousePressed(evt);
            }
        });
        celularText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularTextActionPerformed(evt);
            }
        });
        datosP.add(celularText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 217, 570, 20));

        passText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passText.setForeground(new java.awt.Color(204, 204, 204));
        passText.setText("********");
        passText.setBorder(null);
        passText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTextMousePressed(evt);
            }
        });
        datosP.add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 570, -1));

        pass2Text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pass2Text.setForeground(new java.awt.Color(204, 204, 204));
        pass2Text.setText("********");
        pass2Text.setBorder(null);
        pass2Text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pass2TextMousePressed(evt);
            }
        });
        datosP.add(pass2Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 570, 20));

        foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout fotoLayout = new javax.swing.GroupLayout(foto);
        foto.setLayout(fotoLayout);
        fotoLayout.setHorizontalGroup(
            fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        fotoLayout.setVerticalGroup(
            fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Crear");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("Cancelar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contraseñaL)
                                    .addComponent(pass2L)
                                    .addComponent(nombreL)
                                    .addComponent(usuarioL)
                                    .addComponent(mail2L)
                                    .addComponent(mailL)
                                    .addComponent(fotoL)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(celularL)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(90, 90, 90)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(datosP, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(nombreL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usuarioL)
                        .addGap(18, 18, 18)
                        .addComponent(mailL)
                        .addGap(18, 18, 18)
                        .addComponent(mail2L)
                        .addGap(18, 18, 18)
                        .addComponent(contraseñaL)
                        .addGap(20, 20, 20)
                        .addComponent(pass2L)
                        .addGap(22, 22, 22)
                        .addComponent(celularL)
                        .addGap(26, 26, 26)
                        .addComponent(fotoL)
                        .addGap(18, 18, 18)
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datosP, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void celularTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularTextActionPerformed

    private void nombreTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreTextMousePressed
        if(nombreText.getText().equals("Ingrese su nombre completo")){
            nombreText.setText("");
            nombreText.setForeground(Color.black);
        }
        
        if(usuarioText.getText().isEmpty()){
            usuarioText.setText("Ingrese el nombre con el que iniciará sesión");
            usuarioText.setForeground(Color.gray);
        }
        if(mailText.getText().isEmpty()){
            mailText.setText("Ingrese su e-mail");
            mailText.setForeground(Color.gray);
        }
        if(mail2Text.getText().isEmpty()){
            mail2Text.setText("Repita su e-mail");
            mail2Text.setForeground(Color.gray);
        }
        
        if(String.valueOf(passText.getPassword()).isEmpty()){
            passText.setText("********");
            passText.setForeground(Color.gray);
        }
        if(String.valueOf(pass2Text.getPassword()).isEmpty()){
            pass2Text.setText("********");
            pass2Text.setForeground(Color.gray);
        }
        if(celularText.getText().isEmpty()){
            celularText.setText("Ingrese su número de celular");
            celularText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nombreTextMousePressed

    private void usuarioTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioTextMousePressed
        if(usuarioText.getText().equals("Ingrese el nombre con el que iniciará sesión")){
            usuarioText.setText("");
            usuarioText.setForeground(Color.black);
        }
        
        if(nombreText.getText().isEmpty()){
            nombreText.setText("Ingrese su nombre completo");
            nombreText.setForeground(Color.gray);
        }
        if(mailText.getText().isEmpty()){
            mailText.setText("Ingrese su e-mail");
            mailText.setForeground(Color.gray);
        }
        if(mail2Text.getText().isEmpty()){
            mail2Text.setText("Repita su e-mail");
            mail2Text.setForeground(Color.gray);
        }
        
        if(String.valueOf(passText.getPassword()).isEmpty()){
            passText.setText("********");
            passText.setForeground(Color.gray);
        }
        if(String.valueOf(pass2Text.getPassword()).isEmpty()){
            pass2Text.setText("********");
            pass2Text.setForeground(Color.gray);
        }
        if(celularText.getText().isEmpty()){
            celularText.setText("Ingrese su número de celular");
            celularText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_usuarioTextMousePressed

    private void mailTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailTextMousePressed
        if(mailText.getText().equals("Ingrese su e-mail")){
            mailText.setText("");
            mailText.setForeground(Color.black);
        }
        
        if(nombreText.getText().isEmpty()){
            nombreText.setText("Ingrese su nombre completo");
            nombreText.setForeground(Color.gray);
        }
        if(usuarioText.getText().isEmpty()){
            usuarioText.setText("Ingrese el nombre con el que iniciará sesión");
            usuarioText.setForeground(Color.gray);
        }
        if(mail2Text.getText().isEmpty()){
            mail2Text.setText("Repita su e-mail");
            mail2Text.setForeground(Color.gray);
        }
        
        if(String.valueOf(passText.getPassword()).isEmpty()){
            passText.setText("********");
            passText.setForeground(Color.gray);
        }
        if(String.valueOf(pass2Text.getPassword()).isEmpty()){
            pass2Text.setText("********");
            pass2Text.setForeground(Color.gray);
        }
        if(celularText.getText().isEmpty()){
            celularText.setText("Ingrese su número de celular");
            celularText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_mailTextMousePressed

    private void mail2TextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mail2TextMousePressed
        if(mail2Text.getText().equals("Repita su e-mail")){
            mail2Text.setText("");
            mail2Text.setForeground(Color.black);
        }
        
        if(nombreText.getText().isEmpty()){
            nombreText.setText("Ingrese su nombre completo");
            nombreText.setForeground(Color.gray);
        }
        if(usuarioText.getText().isEmpty()){
            usuarioText.setText("Ingrese el nombre con el que iniciará sesión");
            usuarioText.setForeground(Color.gray);
        }
        if(mailText.getText().isEmpty()){
            mailText.setText("Ingrese su e-mail");
            mailText.setForeground(Color.gray);
        }
        
        if(String.valueOf(passText.getPassword()).isEmpty()){
            passText.setText("********");
            passText.setForeground(Color.gray);
        }
        if(String.valueOf(pass2Text.getPassword()).isEmpty()){
            pass2Text.setText("********");
            pass2Text.setForeground(Color.gray);
        }
        if(celularText.getText().isEmpty()){
            celularText.setText("Ingrese su número de celular");
            celularText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_mail2TextMousePressed

    private void celularTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_celularTextMousePressed
        if(celularText.getText().equals("Ingrese su número de celular")){
            celularText.setText("");
            celularText.setForeground(Color.black);
        }
        
        if(nombreText.getText().isEmpty()){
            nombreText.setText("Ingrese su nombre completo");
            nombreText.setForeground(Color.gray);
        }
        if(usuarioText.getText().isEmpty()){
            usuarioText.setText("Ingrese el nombre con el que iniciará sesión");
            usuarioText.setForeground(Color.gray);
        }
        if(mailText.getText().isEmpty()){
            mailText.setText("Ingrese su e-mail");
            mailText.setForeground(Color.gray);
        }
        
        if(String.valueOf(passText.getPassword()).isEmpty()){
            passText.setText("********");
            passText.setForeground(Color.gray);
        }
        if(String.valueOf(pass2Text.getPassword()).isEmpty()){
            pass2Text.setText("********");
            pass2Text.setForeground(Color.gray);
        }
        if(mail2Text.getText().isEmpty()){
            mail2Text.setText("Repita su e-mail");
            mail2Text.setForeground(Color.gray);
        }
    }//GEN-LAST:event_celularTextMousePressed

    private void passTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTextMousePressed
        if(String.valueOf(passText.getPassword()).equals("********")){
            passText.setText("");
            passText.setForeground(Color.black);
        }
        
        if(nombreText.getText().isEmpty()){
            nombreText.setText("Ingrese su nombre completo");
            nombreText.setForeground(Color.gray);
        }
        if(mailText.getText().isEmpty()){
            mailText.setText("Ingrese su e-mail");
            mailText.setForeground(Color.gray);
        }
        if(mail2Text.getText().isEmpty()){
            mail2Text.setText("Repita su e-mail");
            mail2Text.setForeground(Color.gray);
        }
        
        if(String.valueOf(pass2Text.getPassword()).isEmpty()){
            pass2Text.setText("********");
            pass2Text.setForeground(Color.gray);
        }
        if(usuarioText.getText().isEmpty()){
            usuarioText.setText("Ingrese el nombre con el que iniciará sesión");
            usuarioText.setForeground(Color.gray);
        }
        if(celularText.getText().isEmpty()){
            celularText.setText("Ingrese su número de celular");
            celularText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passTextMousePressed

    private void pass2TextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass2TextMousePressed
        if(String.valueOf(pass2Text.getPassword()).equals("********")){
            pass2Text.setText("");
            pass2Text.setForeground(Color.black);
        }
        
        if(nombreText.getText().isEmpty()){
            nombreText.setText("Ingrese su nombre completo");
            nombreText.setForeground(Color.gray);
        }
        if(mailText.getText().isEmpty()){
            mailText.setText("Ingrese su e-mail");
            mailText.setForeground(Color.gray);
        }
        if(mail2Text.getText().isEmpty()){
            mail2Text.setText("Repita su e-mail");
            mail2Text.setForeground(Color.gray);
        }
        
        if(String.valueOf(passText.getPassword()).isEmpty()){
            passText.setText("********");
            passText.setForeground(Color.gray);
        }
        if(usuarioText.getText().isEmpty()){
            usuarioText.setText("Ingrese el nombre con el que iniciará sesión");
            usuarioText.setForeground(Color.gray);
        }
        if(celularText.getText().isEmpty()){
            celularText.setText("Ingrese su número de celular");
            celularText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_pass2TextMousePressed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        
        
    }//GEN-LAST:event_jPanel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel celularL;
    private javax.swing.JTextField celularText;
    private javax.swing.JLabel contraseñaL;
    private javax.swing.JPanel datosP;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel foto;
    private javax.swing.JLabel fotoL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel mail2L;
    private javax.swing.JTextField mail2Text;
    private javax.swing.JLabel mailL;
    private javax.swing.JTextField mailText;
    private javax.swing.JLabel nombreL;
    private javax.swing.JTextField nombreText;
    private javax.swing.JLabel pass2L;
    private javax.swing.JPasswordField pass2Text;
    private javax.swing.JPasswordField passText;
    private javax.swing.JLabel usuarioL;
    private javax.swing.JTextField usuarioText;
    // End of variables declaration//GEN-END:variables
}
