/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RedSocial;


import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Mau
 */

public class CrearCuentas extends javax.swing.JFrame {
    int xMouse,yMouse;//posicion del mouse en la pantalla

    /**
     * Creates new form CrearCuentas
     */
    int actual;
    public CrearCuentas() {
        initComponents();
        actual = 1;
        setLocationRelativeTo(null);//fija la ventana de login al centro de la pantalla
        comP c = new comP();//creamos una variable para el panel de crear comensal
        
        ShowPanel(c);//mostramos por defecto el panel de crear comensal
        
        resP r= new resP();//creamos una variable para el panel de crear cuenta restaurante
        
        color();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        superior = new javax.swing.JPanel();
        atrasBtn = new javax.swing.JPanel();
        atrasText = new javax.swing.JLabel();
        lateral = new javax.swing.JPanel();
        comBtn = new javax.swing.JPanel();
        comL = new javax.swing.JLabel();
        restBtn = new javax.swing.JPanel();
        restL = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        superior.setOpaque(false);
        superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                superiorMouseDragged(evt);
            }
        });
        superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                superiorMousePressed(evt);
            }
        });

        atrasBtn.setBackground(new java.awt.Color(247, 87, 26));
        atrasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atrasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasBtnMouseExited(evt);
            }
        });

        atrasText.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        atrasText.setForeground(new java.awt.Color(255, 255, 255));
        atrasText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atrasText.setText("←");
        atrasText.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout atrasBtnLayout = new javax.swing.GroupLayout(atrasBtn);
        atrasBtn.setLayout(atrasBtnLayout);
        atrasBtnLayout.setHorizontalGroup(
            atrasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(atrasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(atrasBtnLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(atrasText)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        atrasBtnLayout.setVerticalGroup(
            atrasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
            .addGroup(atrasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(atrasBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(atrasText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout superiorLayout = new javax.swing.GroupLayout(superior);
        superior.setLayout(superiorLayout);
        superiorLayout.setHorizontalGroup(
            superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atrasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1046, Short.MAX_VALUE))
        );
        superiorLayout.setVerticalGroup(
            superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, superiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atrasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Fondo.add(superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 50));

        lateral.setBackground(new java.awt.Color(247, 87, 26));

        comBtn.setBackground(new Color(247,87,26));
        comBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comBtnMouseClicked(evt);
            }
        });

        comL.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        comL.setForeground(new java.awt.Color(255, 255, 255));
        comL.setText("Crear cuenta de comensal");
        comL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout comBtnLayout = new javax.swing.GroupLayout(comBtn);
        comBtn.setLayout(comBtnLayout);
        comBtnLayout.setHorizontalGroup(
            comBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        comBtnLayout.setVerticalGroup(
            comBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        restBtn.setBackground(new Color(247,87,26));
        restBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restBtnMouseClicked(evt);
            }
        });

        restL.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        restL.setForeground(new java.awt.Color(255, 255, 255));
        restL.setText("Crear cuenta de restaurante");
        restL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout restBtnLayout = new javax.swing.GroupLayout(restBtn);
        restBtn.setLayout(restBtnLayout);
        restBtnLayout.setHorizontalGroup(
            restBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restL)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        restBtnLayout.setVerticalGroup(
            restBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout lateralLayout = new javax.swing.GroupLayout(lateral);
        lateral.setLayout(lateralLayout);
        lateralLayout.setHorizontalGroup(
            lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(restBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lateralLayout.setVerticalGroup(
            lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lateralLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(comBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );

        Fondo.add(lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 790));

        content.setOpaque(false);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        Fondo.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 790, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBtnMouseEntered
        atrasBtn.setBackground(Color.white);
        atrasText.setForeground(new Color(247,87,26));
    }//GEN-LAST:event_atrasBtnMouseEntered

    private void atrasBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBtnMouseExited
        atrasText.setForeground(Color.white);
        atrasBtn.setBackground(new Color(247,87,26));
    }//GEN-LAST:event_atrasBtnMouseExited

    private void superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_superiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_superiorMouseDragged

    private void superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_superiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_superiorMousePressed

    private void atrasBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasBtnMouseClicked
        Login nuevo = new Login();
        nuevo.setVisible(true);
        dispose();
    }//GEN-LAST:event_atrasBtnMouseClicked

    private void comBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comBtnMouseClicked
        if(actual == 2){
            comP nuevo = new comP();
            actual = 1;
            ShowPanel(nuevo);
            color();
        }
    }//GEN-LAST:event_comBtnMouseClicked

    private void restBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restBtnMouseClicked
        if(actual == 1){
            resP nuevo = new resP();
            actual = 2;
            ShowPanel(nuevo);
            color();
        }
    }//GEN-LAST:event_restBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel atrasBtn;
    private javax.swing.JLabel atrasText;
    private javax.swing.JPanel comBtn;
    private javax.swing.JLabel comL;
    private javax.swing.JPanel content;
    private javax.swing.JPanel lateral;
    private javax.swing.JPanel restBtn;
    private javax.swing.JLabel restL;
    private javax.swing.JPanel superior;
    // End of variables declaration//GEN-END:variables
    
    private void ShowPanel(JPanel p){
        p.setSize(790,740);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }
    
    private void color(){
        if(actual == 1){
            comBtn.setBackground(Color.white);
            comL.setForeground(new Color(247,87,26));
            
            restBtn.setBackground(new Color(247,87,26));
            restL.setForeground(Color.white);
        }
        
        if(actual==2){
            restBtn.setBackground(Color.white);
            restL.setForeground(new Color(247,87,26));
            
            comBtn.setBackground(new Color(247,87,26));
            comL.setForeground(Color.white);
        }
    }
}
