/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RedSocial;

import Cuentas.Cuenta;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import java.io.IOException;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import Archivos.Ficheros;
import Cuentas.Comensal;
import EDL.ListaDE;

/**
 *
 * @author Mau
 */
public class Login extends javax.swing.JFrame {

    int xMouse, yMouse;//posicion del mouse en la pantalla
    Error error;
    //Error impresiones;
    Ficheros ficheros;
    ListaDE<Cuenta> cuentas;
    boolean usuarioExiste;
    boolean passExiste;

    public Login() {
        initComponents();
        setLocationRelativeTo(null);//fija la ventana de login al centro de la pantalla
        ingresarBtn.setBackground(new Color(242, 242, 242));
        crearCuentaBtn.setBackground(new Color(242, 242, 242));
        error = new Error();
        ficheros = new Ficheros();
        usuarioExiste = false;
        passExiste = false;
        ImageIcon imagen = new ImageIcon("src\\main\\java\\recursos\\imagenes\\fondoLogin.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(imagenLogin.getWidth(), imagenLogin.getHeight(), Image.SCALE_DEFAULT));
        imagenLogin.setIcon(icono);
        cuentas = new ListaDE<Cuenta>();

        leerComensales();


        //impresiones = new Error();
        //impresiones.cambiarTitulo("Lista de cuentas");
        //impresiones.cambiarMensaje(cuentas.toString());
        //impresiones.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barraSuperior = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        FondoDC = new javax.swing.JPanel();
        slogan = new javax.swing.JLabel();
        imagenLogin = new javax.swing.JLabel();
        contraseñaLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        emailText = new javax.swing.JTextField();
        passText = new javax.swing.JPasswordField();
        iniciarSesionLbl = new javax.swing.JLabel();
        ingresarBtn = new javax.swing.JPanel();
        ingresarLabel = new javax.swing.JLabel();
        crearCuentaBtn = new javax.swing.JPanel();
        crearCuentaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraSuperior.setOpaque(false);
        barraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraSuperiorMouseDragged(evt);
            }
        });
        barraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraSuperiorMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });

        exitLabel.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(204, 204, 204));
        exitLabel.setText("X");

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout barraSuperiorLayout = new javax.swing.GroupLayout(barraSuperior);
        barraSuperior.setLayout(barraSuperiorLayout);
        barraSuperiorLayout.setHorizontalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraSuperiorLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 871, Short.MAX_VALUE))
        );
        barraSuperiorLayout.setVerticalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraSuperiorLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        FondoDC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slogan.setFont(new java.awt.Font("Segoe Script", 1, 16)); // NOI18N
        slogan.setForeground(new java.awt.Color(255, 255, 255));
        slogan.setText("Conoce tu ciudad, conoce tu comida");
        FondoDC.add(slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 340, 30));
        FondoDC.add(imagenLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 520));

        jPanel1.add(FondoDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 350, 520));

        contraseñaLbl.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        contraseñaLbl.setText("Contraseña:");
        jPanel1.add(contraseñaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 350, 40));

        emailLbl.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        emailLbl.setText("Usuario:");
        jPanel1.add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 350, 40));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 400, 10));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 400, 10));

        emailText.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        emailText.setForeground(new java.awt.Color(204, 204, 204));
        emailText.setText("Introduce tu nombre de usuario");
        emailText.setBorder(null);
        emailText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailTextMousePressed(evt);
            }
        });
        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });
        jPanel1.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 390, 40));

        passText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passText.setForeground(new java.awt.Color(204, 204, 204));
        passText.setText("********");
        passText.setBorder(null);
        passText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTextMousePressed(evt);
            }
        });
        jPanel1.add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 400, 30));

        iniciarSesionLbl.setFont(new java.awt.Font("Roboto Medium", 0, 48)); // NOI18N
        iniciarSesionLbl.setText("Iniciar sesión");
        jPanel1.add(iniciarSesionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 380, 70));

        ingresarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseExited(evt);
            }
        });

        ingresarLabel.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        ingresarLabel.setText("Ingresar");

        javax.swing.GroupLayout ingresarBtnLayout = new javax.swing.GroupLayout(ingresarBtn);
        ingresarBtn.setLayout(ingresarBtnLayout);
        ingresarBtnLayout.setHorizontalGroup(
            ingresarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ingresarBtnLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(ingresarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        ingresarBtnLayout.setVerticalGroup(
            ingresarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ingresarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(ingresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 150, 50));

        crearCuentaBtn.setBackground(new Color(247,87,26));
        crearCuentaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearCuentaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearCuentaBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearCuentaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearCuentaBtnMouseExited(evt);
            }
        });

        crearCuentaLabel.setBackground(new Color(242,242,242));
        crearCuentaLabel.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        crearCuentaLabel.setText("Crear cuenta");

        javax.swing.GroupLayout crearCuentaBtnLayout = new javax.swing.GroupLayout(crearCuentaBtn);
        crearCuentaBtn.setLayout(crearCuentaBtnLayout);
        crearCuentaBtnLayout.setHorizontalGroup(
            crearCuentaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearCuentaBtnLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(crearCuentaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        crearCuentaBtnLayout.setVerticalGroup(
            crearCuentaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearCuentaBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearCuentaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(crearCuentaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraSuperiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraSuperiorMousePressed

    private void barraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraSuperiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraSuperiorMouseDragged

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        exitLabel.setForeground(Color.white);
        exitBtn.setBackground(new Color(247, 87, 26));
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        exitLabel.setForeground(Color.gray);
        exitBtn.setBackground(Color.white);
    }//GEN-LAST:event_exitBtnMouseExited

    private void ingresarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseEntered
        ingresarLabel.setForeground(Color.white);
        ingresarBtn.setBackground(new Color(247, 87, 26));
    }//GEN-LAST:event_ingresarBtnMouseEntered

    private void ingresarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseExited
        ingresarLabel.setForeground(Color.black);
        ingresarBtn.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_ingresarBtnMouseExited

    private void crearCuentaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearCuentaBtnMouseEntered
        crearCuentaLabel.setForeground(Color.white);
        crearCuentaBtn.setBackground(new Color(247, 87, 26));
    }//GEN-LAST:event_crearCuentaBtnMouseEntered

    private void crearCuentaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearCuentaBtnMouseExited
        crearCuentaLabel.setForeground(Color.black);
        crearCuentaBtn.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_crearCuentaBtnMouseExited

    private void emailTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTextMousePressed
        if (emailText.getText().equals("Introduce tu nombre de usuario")) {
            emailText.setText("");
            emailText.setForeground(Color.black);
        }

        if (String.valueOf(passText.getPassword()).isEmpty()) {
            passText.setText("********");
            passText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_emailTextMousePressed

    private void passTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTextMousePressed
        if (String.valueOf(passText.getPassword()).equals("********")) {
            passText.setText("");
            passText.setForeground(Color.black);
        }

        if (emailText.getText().isEmpty()) {
            emailText.setText("Introduce tu nombre de usuario");
            emailText.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passTextMousePressed

    private void crearCuentaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearCuentaBtnMouseClicked
        CrearCuentas nuevo = new CrearCuentas();
        nuevo.setVisible(true);
        dispose();
    }//GEN-LAST:event_crearCuentaBtnMouseClicked

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void ingresarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseClicked
        if (verificarCuenta(emailText.getText(), String.valueOf(passText.getPassword()))) {
            Sitio l = new Sitio(cuentas, posicion(emailText.getText()));
            l.setVisible(true);
            this.dispose();

        } else {
            if (usuarioExiste == false && passExiste == false) {
                error.cambiarMensaje("usuario y contraseña incorrectos");
                error.setVisible(true);
            } else {
                if (usuarioExiste == true && passExiste == false) {
                    error.cambiarMensaje(" contraseña incorrecta");
                    error.setVisible(true);
                    usuarioExiste = false;
                }
            }
        }

    }//GEN-LAST:event_ingresarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoDC;
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JLabel contraseñaLbl;
    private javax.swing.JPanel crearCuentaBtn;
    private javax.swing.JLabel crearCuentaLabel;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailText;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel imagenLogin;
    private javax.swing.JPanel ingresarBtn;
    private javax.swing.JLabel ingresarLabel;
    private javax.swing.JLabel iniciarSesionLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField passText;
    private javax.swing.JLabel slogan;
    // End of variables declaration//GEN-END:variables

    /**
     * lee cada uno de los archivos de la carpeta comensales y los añade como
     * objetos de tipo comensal a la lista cuentas
     */
    public void leerComensales() {
        String directorio = "src\\main\\java\\recursos\\Cuentas\\Comensales";
        try ( DirectoryStream<Path> ds = Files.newDirectoryStream(Paths.get(directorio))) {
            for (Path ruta : ds) {
                Comensal c = ficheros.leerComensal("" + ruta.getFileName());
                cuentas.add(c);
            }
        } catch (IOException e) {
            error.cambiarTitulo("IO exception e");
            error.cambiarMensaje("" + e.getMessage());
        }
    }

    public boolean verificarCuenta(String usuario, String pass) {
        boolean res = false;

        for (int i = 0; i < cuentas.tamaño() && res != true; i++) {
            if (cuentas.obtenerPos(i).getUsuario().equals(usuario)) {
                usuarioExiste = true;
            }
            if (cuentas.obtenerPos(i).getContraseña().equals(pass)) {
                passExiste = true;
            }
            if (usuarioExiste == true && passExiste == true) {
                res = true;

            }

        }
        return res;
    }

    /**
     * devuelve la posicion del usuario en la lista
     */
    public int posicion(String usuario) {
        boolean existe = false;
        int res = 0;

        for (int i = 0; i < cuentas.tamaño() && existe != true; i++) {
            res++;
            if (cuentas.obtenerPos(i).getUsuario().equals(usuario)) {
                existe = true;

            }

        }
        return res - 1;

    }
}
