/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RedSocial;

import Cuentas.Comensal;
import Cuentas.Restaurante;
import java.awt.Color;

/**
 *
 * @author Mau
 */
public class resP extends javax.swing.JPanel {

    Color naranjaSuave;
    Color naranja;
    CrearCuentas frame;

    public resP() {
        initComponents();
        naranja = new Color(247, 87, 26);
        naranjaSuave = new Color(250, 183, 44);
        crearBtn.setBackground(naranja);
        crearLbl.setForeground(Color.white);
        cancelarbtn.setBackground(naranja);
        cancelarlbl.setForeground(Color.white);
        CrearCuentas x = null;

        frame = x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreL = new javax.swing.JLabel();
        usuarioL = new javax.swing.JLabel();
        contraseñaL = new javax.swing.JLabel();
        mailL = new javax.swing.JLabel();
        pass2L = new javax.swing.JLabel();
        mail2L = new javax.swing.JLabel();
        datosP = new javax.swing.JPanel();
        nombreText = new javax.swing.JTextField();
        usuarioText = new javax.swing.JTextField();
        mailText = new javax.swing.JTextField();
        mail2Text = new javax.swing.JTextField();
        celularText = new javax.swing.JTextField();
        passText = new javax.swing.JPasswordField();
        pass2Text = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        wifi = new java.awt.Checkbox();
        zniños = new java.awt.Checkbox();
        delivery = new java.awt.Checkbox();
        diasYHorasL = new javax.swing.JLabel();
        especialidadL = new javax.swing.JLabel();
        atencion = new javax.swing.JScrollPane();
        atencionText = new javax.swing.JTextArea();
        especialidadText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dirText = new javax.swing.JTextField();
        celularL = new javax.swing.JLabel();
        fotoL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        foto = new javax.swing.JPanel();
        crearBtn = new javax.swing.JPanel();
        crearLbl = new javax.swing.JLabel();
        cancelarbtn = new javax.swing.JPanel();
        cancelarlbl = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreL.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nombreL.setText("Nombre");
        add(nombreL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, 30));

        usuarioL.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        usuarioL.setText("Nombre de usuario:");
        add(usuarioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 30));

        contraseñaL.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        contraseñaL.setText("Contraseña:");
        add(contraseñaL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 30));

        mailL.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mailL.setText("E-mail:");
        add(mailL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 20));

        pass2L.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        pass2L.setText("Repita la contraseña:");
        add(pass2L, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        mail2L.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mail2L.setText("repita su E-mail:");
        add(mail2L, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, 30));

        datosP.setOpaque(false);
        datosP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nombreText.setForeground(new java.awt.Color(204, 204, 204));
        nombreText.setText("Ingrese el nombre de su restaurante");
        nombreText.setBorder(null);
        nombreText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreTextMousePressed(evt);
            }
        });
        datosP.add(nombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 536, 30));

        usuarioText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        usuarioText.setForeground(new java.awt.Color(204, 204, 204));
        usuarioText.setText("Ingrese el nombre con el que iniciará sesión");
        usuarioText.setBorder(null);
        usuarioText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioTextMousePressed(evt);
            }
        });
        datosP.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 536, 28));

        mailText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mailText.setForeground(new java.awt.Color(204, 204, 204));
        mailText.setText("Ingrese su e-mail");
        mailText.setBorder(null);
        mailText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mailTextMousePressed(evt);
            }
        });
        datosP.add(mailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 536, 27));

        mail2Text.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mail2Text.setForeground(new java.awt.Color(204, 204, 204));
        mail2Text.setText("Repita su e-mail");
        mail2Text.setBorder(null);
        mail2Text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mail2TextMousePressed(evt);
            }
        });
        datosP.add(mail2Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 536, 29));

        celularText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        celularText.setForeground(new java.awt.Color(204, 204, 204));
        celularText.setText("Ingrese su número de celular");
        celularText.setBorder(null);
        celularText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                celularTextMousePressed(evt);
            }
        });
        datosP.add(celularText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 536, 35));

        passText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passText.setForeground(new java.awt.Color(204, 204, 204));
        passText.setText("********");
        passText.setBorder(null);
        passText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTextMousePressed(evt);
            }
        });
        datosP.add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 536, 30));

        pass2Text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pass2Text.setForeground(new java.awt.Color(204, 204, 204));
        pass2Text.setText("********");
        pass2Text.setBorder(null);
        pass2Text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pass2TextMousePressed(evt);
            }
        });
        datosP.add(pass2Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 536, 28));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setText("Características que pueda presentar su restaurante");
        datosP.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        wifi.setBackground(new java.awt.Color(255, 255, 255));
        wifi.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        wifi.setLabel("Wi-fi");
        datosP.add(wifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        zniños.setBackground(new java.awt.Color(255, 255, 255));
        zniños.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        zniños.setLabel("Zona para niños");
        datosP.add(zniños, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        delivery.setBackground(new java.awt.Color(255, 255, 255));
        delivery.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        delivery.setLabel("Delivery");
        datosP.add(delivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        diasYHorasL.setText("Días y horario de atención:");
        datosP.add(diasYHorasL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        especialidadL.setText("Especialidad de la casa:");
        datosP.add(especialidadL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        atencion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        atencion.setForeground(new java.awt.Color(204, 204, 204));
        atencion.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        atencion.setToolTipText("especifique los dias y horarios en los que atiende (opcional). \nEsta información se mostrará tal cual la escriba");

        atencionText.setColumns(20);
        atencionText.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        atencionText.setForeground(new java.awt.Color(204, 204, 204));
        atencionText.setRows(5);
        atencionText.setText("Ingrese los horarios y dias de atencion(opcional)");
        atencionText.setToolTipText("");
        atencionText.setBorder(null);
        atencionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                atencionTextMousePressed(evt);
            }
        });
        atencion.setViewportView(atencionText);

        datosP.add(atencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 440, 340, 47));

        especialidadText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        especialidadText.setForeground(new java.awt.Color(204, 204, 204));
        especialidadText.setText("Escriba el platillo por el que se caracteriza");
        especialidadText.setBorder(null);
        especialidadText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                especialidadTextMousePressed(evt);
            }
        });
        datosP.add(especialidadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 350, -1));

        jLabel2.setText("Direccion:");
        datosP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        dirText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        dirText.setForeground(new java.awt.Color(204, 204, 204));
        dirText.setText("Ingrese la direccion de su establecimiento");
        dirText.setBorder(null);
        dirText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dirTextMousePressed(evt);
            }
        });
        datosP.add(dirText, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 550, 430, -1));

        add(datosP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        celularL.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        celularL.setText("Numero de celular:");
        add(celularL, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 30));

        fotoL.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fotoL.setText("Foto de perfil:");
        add(fotoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("CREAR CUENTA DE TIPO RESTAURANTE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 376, 23));

        foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout fotoLayout = new javax.swing.GroupLayout(foto);
        foto.setLayout(fotoLayout);
        fotoLayout.setHorizontalGroup(
            fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        fotoLayout.setVerticalGroup(
            fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        crearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearBtnMouseExited(evt);
            }
        });
        crearBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearLbl.setText("Crear cuenta");
        crearLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearLblMouseClicked(evt);
            }
        });
        crearBtn.add(crearLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        add(crearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 670, 120, 40));

        cancelarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarbtnMouseExited(evt);
            }
        });

        cancelarlbl.setForeground(new java.awt.Color(255, 255, 255));
        cancelarlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarlbl.setText("Cancelar");

        javax.swing.GroupLayout cancelarbtnLayout = new javax.swing.GroupLayout(cancelarbtn);
        cancelarbtn.setLayout(cancelarbtnLayout);
        cancelarbtnLayout.setHorizontalGroup(
            cancelarbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        cancelarbtnLayout.setVerticalGroup(
            cancelarbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(cancelarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 670, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreTextMousePressed
        defecto("nombreText");
    }//GEN-LAST:event_nombreTextMousePressed

    private void usuarioTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioTextMousePressed
        defecto("usuarioText");
    }//GEN-LAST:event_usuarioTextMousePressed

    private void mailTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailTextMousePressed
        defecto("mailText");
    }//GEN-LAST:event_mailTextMousePressed

    private void mail2TextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mail2TextMousePressed
        defecto("mail2Text");
    }//GEN-LAST:event_mail2TextMousePressed

    private void passTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTextMousePressed
        defecto("passText");
    }//GEN-LAST:event_passTextMousePressed

    private void pass2TextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass2TextMousePressed
        defecto("pass2Text");
    }//GEN-LAST:event_pass2TextMousePressed

    private void celularTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_celularTextMousePressed
        defecto("celularText");
    }//GEN-LAST:event_celularTextMousePressed

    private void especialidadTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_especialidadTextMousePressed
        defecto("especialidadText");
    }//GEN-LAST:event_especialidadTextMousePressed

    private void atencionTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atencionTextMousePressed
        defecto("atencionText");
    }//GEN-LAST:event_atencionTextMousePressed

    private void dirTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dirTextMousePressed
        defecto("dirText");
    }//GEN-LAST:event_dirTextMousePressed

    private void crearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMouseEntered
        crearBtn.setBackground(naranjaSuave);

    }//GEN-LAST:event_crearBtnMouseEntered

    private void crearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMouseExited
        crearBtn.setBackground(naranja);

    }//GEN-LAST:event_crearBtnMouseExited

    private void crearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMouseClicked
        Restaurante Restaurante = new Restaurante();
        Restaurante.crearRestaurante(new Restaurante(nombreText.getText(), usuarioText.getText(), mailText.getText(), passText.getText(), celularText.getText()));

    }//GEN-LAST:event_crearBtnMouseClicked

    private void cancelarbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarbtnMouseEntered
        cancelarbtn.setBackground(naranjaSuave);
    }//GEN-LAST:event_cancelarbtnMouseEntered

    private void cancelarbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarbtnMouseExited
        cancelarbtn.setBackground(naranja);
    }//GEN-LAST:event_cancelarbtnMouseExited

    private void cancelarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarbtnMouseClicked
        Login nuevo = new Login();
        nuevo.setVisible(true);
        frame.cerrar();
    }//GEN-LAST:event_cancelarbtnMouseClicked

    private void crearLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearLblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_crearLblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane atencion;
    private javax.swing.JTextArea atencionText;
    private javax.swing.JPanel cancelarbtn;
    private javax.swing.JLabel cancelarlbl;
    private javax.swing.JLabel celularL;
    private javax.swing.JTextField celularText;
    private javax.swing.JLabel contraseñaL;
    private javax.swing.JPanel crearBtn;
    private javax.swing.JLabel crearLbl;
    private javax.swing.JPanel datosP;
    private java.awt.Checkbox delivery;
    private javax.swing.JLabel diasYHorasL;
    private javax.swing.JTextField dirText;
    private javax.swing.JLabel especialidadL;
    private javax.swing.JTextField especialidadText;
    private javax.swing.JPanel foto;
    private javax.swing.JLabel fotoL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel mail2L;
    private javax.swing.JTextField mail2Text;
    private javax.swing.JLabel mailL;
    private javax.swing.JTextField mailText;
    private javax.swing.JLabel nombreL;
    private javax.swing.JTextField nombreText;
    private javax.swing.JLabel pass2L;
    private javax.swing.JPasswordField pass2Text;
    private javax.swing.JPasswordField passText;
    private javax.swing.JLabel usuarioL;
    private javax.swing.JTextField usuarioText;
    private java.awt.Checkbox wifi;
    private java.awt.Checkbox zniños;
    // End of variables declaration//GEN-END:variables

    public void defecto(String l) {

        if (l.equals("nombreText") && nombreText.getText().equals("Ingrese el nombre de su restaurante")) {
            nombreText.setText("");
            nombreText.setForeground(Color.black);
        } else {
            if (nombreText.getText().isEmpty()) {
                nombreText.setText("Ingrese el nombre de su restaurante");
                nombreText.setForeground(Color.gray);
            }
        }

        if (l.equals("usuarioText") && usuarioText.getText().equals("Ingrese el nombre con el que iniciará sesión")) {
            usuarioText.setText("");
            usuarioText.setForeground(Color.black);
        } else {
            if (usuarioText.getText().isEmpty()) {
                usuarioText.setText("Ingrese el nombre con el que iniciará sesión");
                usuarioText.setForeground(Color.gray);
            }
        }

        if (l.equals("mailText") && mailText.getText().equals("Ingrese su e-mail")) {
            mailText.setText("");
            mailText.setForeground(Color.black);
        } else {
            if (mailText.getText().isEmpty()) {
                mailText.setText("Ingrese su e-mail");
                mailText.setForeground(Color.gray);
            }
        }

        if (l.equals("mail2Text") && mail2Text.getText().equals("Repita su e-mail")) {
            mail2Text.setText("");
            mail2Text.setForeground(Color.black);
        } else {
            if (mail2Text.getText().isEmpty()) {
                mail2Text.setText("Repita su e-mail");
                mail2Text.setForeground(Color.gray);
            }
        }

        if (l.equals("passText") && passText.getText().equals("********")) {
            passText.setText("");
            passText.setForeground(Color.black);
        } else {
            if (String.valueOf(passText.getPassword()).isEmpty()) {
                passText.setText("********");
                passText.setForeground(Color.gray);
            }
        }

        if (l.equals("pass2Text") && pass2Text.getText().equals("********")) {
            pass2Text.setText("");
            pass2Text.setForeground(Color.black);
        } else {
            if (String.valueOf(pass2Text.getPassword()).isEmpty()) {
                pass2Text.setText("********");
                pass2Text.setForeground(Color.gray);
            }
        }

        if (l.equals("celularText") && celularText.getText().equals("Ingrese su número de celular")) {
            celularText.setText("");
            celularText.setForeground(Color.black);
        } else {
            if (celularText.getText().isEmpty()) {
                celularText.setText("Ingrese su número de celular");
                celularText.setForeground(Color.gray);
            }
        }

        if (l.equals("especialidadText") && especialidadText.getText().equals("Escriba el platillo por el que se caracteriza")) {
            especialidadText.setText("");
            especialidadText.setForeground(Color.black);
        } else {
            if (especialidadText.getText().isEmpty()) {
                especialidadText.setText("Escriba el platillo por el que se caracteriza");
                especialidadText.setForeground(Color.gray);
            }
        }

        if (l.equals("atencionText") && atencionText.getText().equals("Ingrese los horarios y dias de atencion(opcional)")) {
            atencionText.setText("");
            atencionText.setForeground(Color.black);
        } else {
            if (atencionText.getText().isEmpty()) {
                atencionText.setText("Ingrese los horarios y dias de atencion(opcional)");
                atencionText.setForeground(Color.gray);
            }

        }

        if (l.equals("dirText") && dirText.getText().equals("Ingrese la direccion de su establecimiento")) {
            dirText.setText("");
            dirText.setForeground(Color.black);
        } else {
            if (dirText.getText().isEmpty()) {
                dirText.setText("Ingrese la direccion de su establecimiento");
                dirText.setForeground(Color.gray);
            }
        }
    }
}
